### ISSUE TITLE
Setting NCx_LS = 1 doesn't seem to work

### ISSUE THREAD

**Issue by mhx** [simontheu/lb-gps-linux#4]
According to the Silicon Labs Si53xx-RM docs, most (all?) Si53xx chips should support NCx_LS = 1 in addition to even divisors. `lb-gps-linux` does allow setting this value, but the (big) GPS Reference Clock behaves strangely when actually setting NCx_LS = 1. For example, with
```
./lb-gps-linux /dev/hidraw3 --bw 15 --gps 2000000 --n31 1 --n2_ls 250 --n2_hs 10 --n1_hs 10 --nc1_ls 1 --nc2_ls 50
```
the GPSDO's PLL actually locks and produces a clean 10MHz signal on channel 2, but the signal on channel 1 looks completely off:
![screenshot-1](https://gist.githubusercontent.com/mhx/df1563bec10b23efb9eff4ada55b11e8/raw/746bf13625c65f63a9665a3e51cbac11a085ed46/NCeq1.png)

When instead setting NC1_LS = 2 and adjusting N1_HS and NC2_LS accordingly, keeping everything else the same
```
./lb-gps-linux /dev/hidraw3 --bw 15 --gps 2000000 --n31 1 --n2_ls 250 --n2_hs 10 --n1_hs 5 --nc1_ls 2 --nc2_ls 100
```
the resulting signal looks as expected:
![screenshot-2](https://gist.githubusercontent.com/mhx/df1563bec10b23efb9eff4ada55b11e8/raw/746bf13625c65f63a9665a3e51cbac11a085ed46/NCeq2-2.png)
(Note how both gain and timebase are very different in the two screenshots. Also note that 500MHz is way beyond the bandwidth of the scope, so the real amplitude is likely quite different.)

I've verified with the "official" Windows tool for the GPS Reference Clock that setting NCx_LS = 1 is not allowed, it'll always change back to a value of 2.

Now, my questions are:
1. Am I correct that, at least in theory, the Si53xx (didn't open the clock yet, so not sure exactly which one it is) should support NCx_LS = 1?
2. If so, is there a bug lurking somewhere? I'd guess this would most likely be in the GPSDO firmware itself, as the `lb-gps-linux` code doesn't seem to be doing anything too fancy.
3. If not, is the reason documented anywhere?
Thanks!

**Comment by simontheu** [comment]
Hi,

NCx_LS cannot be 1 in CMOS mode.

Regards
Simon

**Comment by mhx** [comment]
Oh wow, that's interesting! I just had another look and there doesn't seem to be any (obvious) note of this behaviour in any of the Silicon Labs datasheets. Anyhow, that likely explains what's going on!

Thanks for the quick update!

**Comment by simontheu** [comment]
We opened a support request with them, and this was the answer.
